In [23]:
import pandas as pd

In [24]:
data = pd.read_csv("https://raw.githubusercontent.com/amankharwal/SMS-Spam-Detection/master/spam.csv", encoding= 'latin-1')

In [27]:
data.head()

class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [28]:
data.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis=1,inplace=True)

In [29]:
data.head()

class                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [30]:
data.shape

(5572, 2)

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [34]:
cv=CountVectorizer(lowercase=True,stop_words={'english'},ngram_range=(1,2))

In [35]:
cv.fit(data.message)

CountVectorizer(ngram_range=(1, 2), stop_words={'english'})

In [36]:
X=cv.transform(data.message)

In [38]:
X

<5572x50319 sparse matrix of type '<class 'numpy.int64'>'
	with 147795 stored elements in Compressed Sparse Row format>

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, data["class"], test_size=0.33, random_state=42)

In [44]:
nb_clf=MultinomialNB()

In [45]:
nb_clf.fit(X_train,y_train)

MultinomialNB()

In [46]:
from sklearn.linear_model import LogisticRegression

In [47]:
lr_clf=LogisticRegression()

In [48]:
lr_clf.fit(X_train,y_train)

LogisticRegression()

In [49]:
from sklearn.ensemble import RandomForestClassifier

In [50]:
rf=RandomForestClassifier()

In [51]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [52]:
from sklearn.model_selection import cross_val_score

In [53]:
nb_scores=cross_val_score(nb_clf,X_train,y_train,cv=4,n_jobs=-1)

In [55]:
nb_scores

array([0.98715203, 0.98499464, 0.98392283, 0.97106109])

In [54]:
nb_scores.mean()

0.9817826495085045

In [56]:
lr_scores=cross_val_score(lr_clf,X_train,y_train,cv=4,n_jobs=-1)

In [57]:
lr_scores

array([0.98715203, 0.98392283, 0.96677385, 0.97320472])

In [58]:
lr_scores.mean()

0.977763356904003

In [59]:
rf_scores=cross_val_score(rf,X_train,y_train,cv=4,n_jobs=-1)

In [60]:
rf_scores

array([0.96359743, 0.97106109, 0.95605573, 0.95819936])

In [61]:
rf_scores.mean()

0.9622284036896016

In [62]:
#using nb classifier finally

In [63]:
predictions=nb_clf.predict(X_test)

In [64]:
from sklearn.metrics import accuracy_score

In [65]:
accuracy_score(y_test,predictions)

0.9760739532354541

In [66]:
from sklearn.metrics import classification_report

In [68]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         ham       0.99      0.98      0.99      1587
        spam       0.90      0.92      0.91       252

    accuracy                           0.98      1839
   macro avg       0.95      0.95      0.95      1839
weighted avg       0.98      0.98      0.98      1839



In [69]:
import joblib

In [70]:
joblib.dump(cv,"cv.joblib")

['cv.joblib']

In [71]:
joblib.dump(nb_clf,"model.joblib")

['model.joblib']

In [72]:
X_test

<1839x50319 sparse matrix of type '<class 'numpy.int64'>'
	with 49376 stored elements in Compressed Sparse Row format>

In [73]:
X

<5572x50319 sparse matrix of type '<class 'numpy.int64'>'
	with 147795 stored elements in Compressed Sparse Row format>

In [74]:
data

class                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [79]:
data["message"][100]

'No..but heard abt tat..'